fixtures:
  symlinks:
    pixelated: "#{source_dir}"
    lsb: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/lsb"
    common: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/common"
    rsyslog: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/rsyslog"
    concat: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/concat"
    apache: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/apache"
    templatewlv: "#{source_dir}/spec/fixtures/modules/leap_platform/puppet/modules/templatewlv"
  repositories:
    leap_platform:
      repo: "https://0xacab.org/pixelated/platform.git"
      flags: "--recursive"

